///* =========================================================
// * ====                   WARNING                        ===
// * =========================================================
// * The code in this tab has been generated from the GUI form
// * designer and care should be taken when editing this file.
// * Only add/edit code inside the event handlers i.e. only
// * use lines between the matching comment tags. e.g.

// void myBtnEvents(GButton button) { //_CODE_:button1:12356:
//     // It is safe to enter your event code here  
// } //_CODE_:button1:12356:
 
// * Do not rename this tab!
// * =========================================================
// */

//public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:786335:
//  println("button1 - GButton >> GEvent." + event + " @ " + millis());
//} //_CODE_:button1:786335:

//public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:red_slider:717472:
//  println("red_slider - GCustomSlider >> GEvent." + event + " @ " + millis());
//} //_CODE_:red_slider:717472:

//public void timer1_Action1(GTimer source) { //_CODE_:timer1:971576:
//  println("timer1 - GTimer >> an event occured @ " + millis());
//} //_CODE_:timer1:971576:



//// Create all the GUI controls. 
//// autogenerated do not edit
//public void createGUI(){
//  G4P.messagesEnabled(false);
//  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
//  G4P.setMouseOverEnabled(false);
//  surface.setTitle("Sketch Window");
//  view1 = new GView(this, 178, 155, 80, 60, JAVA2D);
//  view2 = new GView(this, 178, 155, 80, 60, JAVA2D);
//  button1 = new GButton(this, 178, 170, 80, 30);
//  button1.setText("Face text");
//  button1.setLocalColorScheme(GCScheme.SCHEME_12);
//  button1.addEventHandler(this, "button1_click1");
//  red_slider = new GCustomSlider(this, 232, 75, 100, 40, "grey_blue");
//  red_slider.setLimits(0.5, 0.0, 1.0);
//  red_slider.setNumberFormat(G4P.DECIMAL, 2);
//  red_slider.setOpaque(false);
//  red_slider.addEventHandler(this, "custom_slider1_change1");
//  timer1 = new GTimer(this, this, "timer1_Action1", 1000);
//}

//// Variable declarations 
//// autogenerated do not edit
//GView view1; 
//GView view2; 
//GButton button1; 
//GCustomSlider red_slider; 
//GTimer timer1; 
